/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Google login URL */
        get: operations["AuthController_googleAuthUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to Google login page */
        get: operations["AuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback and session creation */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/microsoft/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Microsoft login URL */
        get: operations["AuthController_microsoftAuthUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/microsoft/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to Microsoft login page */
        get: operations["AuthController_microsoftLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/microsoft/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Microsoft OAuth callback and session creation */
        get: operations["AuthController_microsoftCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List linked SSO providers for the current user */
        get: operations["AuthController_listLinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/links/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink an SSO provider from the current user */
        delete: operations["AuthController_unlinkProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear auth cookie and logout */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile of authenticated user */
        get: operations["AuthController_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all reservations (Admin only) */
        get: operations["ReservationsController_findAll"];
        put?: never;
        /** Create a new reservation (authenticated user) */
        post: operations["ReservationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/cancel/{cuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cancel a reservation using the unique CUID from email */
        patch: operations["ReservationsController_cancelByCuid"];
        trace?: never;
    };
    "/reservations/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get occupied time slots for a date (public, no PII) */
        get: operations["ReservationsController_getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/verify/{cuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify reservation by QR code CUID (Admin only) */
        get: operations["ReservationsController_verifyByCuid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a reservation as admin (no date restrictions) */
        post: operations["ReservationsController_adminCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/no-shows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all no-shows (Admin only) */
        get: operations["ReservationsController_getNoShows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{userId}/no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Unblock user from reservations (Admin only) */
        patch: operations["ReservationsController_unBlockUser"];
        trace?: never;
    };
    "/reservations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update reservation status (Admin only) */
        patch: operations["ReservationsController_updateStatus"];
        trace?: never;
    };
    "/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a reservation (Admin only) */
        delete: operations["ReservationsController_remove"];
        options?: never;
        head?: never;
        /** Update a reservation (Admin only) */
        patch: operations["ReservationsController_update"];
        trace?: never;
    };
    "/roster/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all roster games with entries */
        get: operations["RosterController_findAllGames"];
        put?: never;
        /** Create a new roster game (Admin only) */
        post: operations["RosterController_createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a roster game (Admin only) */
        delete: operations["RosterController_deleteGame"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all roster entries */
        get: operations["RosterController_findAllEntries"];
        put?: never;
        /** Add a roster entry with optional image (Admin only) */
        post: operations["RosterController_createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a roster entry (Admin only) */
        delete: operations["RosterController_deleteEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all timetable entries */
        get: operations["TimetableController_findAll"];
        put?: never;
        /** Create a timetable entry (Admin only) */
        post: operations["TimetableController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timetable/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a timetable entry (Admin only) */
        delete: operations["TimetableController_remove"];
        options?: never;
        head?: never;
        /** Update a timetable entry (Admin only) */
        patch: operations["TimetableController_update"];
        trace?: never;
    };
    "/settings/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public-facing settings (no auth required) */
        get: operations["SettingsController_getPublicSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get inventory counts (public) */
        get: operations["SettingsController_getInventorySettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the single form */
        get: operations["SettingsController_getForm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the single form */
        patch: operations["SettingsController_updateForm"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all settings (Admin only) */
        get: operations["SettingsController_getAllSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a setting (Admin only) */
        patch: operations["SettingsController_updateSetting"];
        trace?: never;
    };
    "/settings/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all admin users (Admin only) */
        get: operations["SettingsController_getAllAdmins"];
        put?: never;
        /** Add a new admin (Admin only) */
        post: operations["SettingsController_createAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/admins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an admin (Admin only) */
        delete: operations["SettingsController_removeAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get upcoming events (public) */
        get: operations["EventsController_findUpcoming"];
        put?: never;
        /** Create a new event (Admin only) */
        post: operations["EventsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all events (Admin only) */
        get: operations["EventsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an event (Admin only) */
        delete: operations["EventsController_delete"];
        options?: never;
        head?: never;
        /** Update an event (Admin only) */
        patch: operations["EventsController_update"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users with filters (Admin only) */
        get: operations["UsersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/whitelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending SSO whitelist entries (Admin only) */
        get: operations["UsersController_listWhitelist"];
        put?: never;
        /** Pre-authorize an external SSO email for a user (Admin only) */
        post: operations["UsersController_createWhitelist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/whitelist/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a whitelist entry (Admin only) */
        delete: operations["UsersController_deleteWhitelist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user detail (Admin only) */
        get: operations["UsersController_getById"];
        put?: never;
        post?: never;
        /** Delete a user and cascade their reservations (Admin only) */
        delete: operations["UsersController_delete"];
        options?: never;
        head?: never;
        /** Update a user (Admin only) */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/users/{id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote user to admin (Admin only) */
        post: operations["UsersController_promote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Demote user from admin (Admin only) */
        delete: operations["UsersController_demote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/sso/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink an SSO provider from a user (Admin only) */
        delete: operations["UsersController_unlinkSso"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GoogleAuthUrlResponseDto: {
            /**
             * @description Google OAuth login URL
             * @example https://accounts.google.com/o/oauth2/v2/auth?...
             */
            url: string;
        };
        MicrosoftAuthUrlResponseDto: {
            /**
             * @description Microsoft OAuth login URL
             * @example https://login.microsoftonline.com/.../oauth2/v2.0/authorize?...
             */
            url: string;
        };
        LinkedProviderDto: {
            id: number;
            ssoId: string;
        };
        LinkedProvidersResponseDto: {
            google: components["schemas"]["LinkedProviderDto"][];
            microsoft: components["schemas"]["LinkedProviderDto"][];
        };
        LogoutResponseDto: {
            /** @example true */
            success: boolean;
        };
        AuthProfileResponseDto: {
            id: number;
            name: string | null;
            email: string;
            sNumber: string;
            /** @description Whether the authenticated user is an admin user */
            isAdmin: boolean;
        };
        CreateReservationDto: {
            /**
             * @example pc
             * @enum {string}
             */
            inventory: "pc" | "ps5" | "switch";
            /** @example 2 */
            controllers: number;
            /** @example 2026-02-28T10:00:00.000Z */
            startTime: string;
            /** @example 2026-02-28T12:00:00.000Z */
            endTime: string;
        };
        /** @enum {string} */
        ReservationStatus: "RESERVED" | "CANCELLED" | "PRESENT" | "NO_SHOW";
        Reservation: {
            id: number;
            cuid: string;
            userId: number;
            controllers: number;
            email: string;
            inventory: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            status: components["schemas"]["ReservationStatus"];
        };
        HttpExceptionDto: {
            /** @example 400 */
            statusCode: number;
            /** @example Validation or business rule violation */
            message: string | string[];
            /** @example Bad Request */
            error: string;
        };
        ReservationSlotDto: {
            /** @example pc */
            inventory: string;
            /** @example 2 */
            controllers: number;
            /**
             * Format: date-time
             * @example 2026-02-28T10:00:00.000Z
             */
            startTime: string;
            /**
             * Format: date-time
             * @example 2026-02-28T12:00:00.000Z
             */
            endTime: string;
        };
        ReservationVerificationDto: {
            /** @example cm9x8k2df0000a1b2c3d4e5f6 */
            cuid: string;
            /** @example student@student.ap.be */
            email: string;
            /** @example s123456 */
            sNumber: string;
            /**
             * @example pc
             * @enum {string}
             */
            inventory: "pc" | "ps5" | "switch";
            /** @example 2 */
            controllers: number;
            /**
             * Format: date-time
             * @example 2026-02-28T10:00:00.000Z
             */
            startTime: string;
            /**
             * Format: date-time
             * @example 2026-02-28T12:00:00.000Z
             */
            endTime: string;
            /** @enum {string} */
            status: "RESERVED" | "CANCELLED" | "PRESENT" | "NO_SHOW";
        };
        AdminCreateReservationDto: {
            /** @example s123456 */
            sNumber?: string;
            /** @example student@student.ap.be */
            email: string;
            /**
             * @example pc
             * @enum {string}
             */
            inventory: "pc" | "ps5" | "switch";
            /** @example 2 */
            controllers: number;
            /** @example 2026-02-28T10:00:00.000Z */
            startTime: string;
            /** @example 2026-02-28T12:00:00.000Z */
            endTime: string;
        };
        UpdateReservationStatusDto: {
            /** @enum {string} */
            status: "RESERVED" | "CANCELLED" | "PRESENT" | "NO_SHOW";
        };
        UpdateReservationDto: {
            /** @example student@student.ap.be */
            email?: string;
            /** @example s123456 */
            sNumber?: string;
            /**
             * @example pc
             * @enum {string}
             */
            inventory?: "pc" | "ps5" | "switch";
            /** @example 2 */
            controllers?: number;
            /** @example 2026-02-28T10:00:00.000Z */
            startTime?: string;
            /** @example 2026-02-28T12:00:00.000Z */
            endTime?: string;
        };
        RosterGame: {
            id: number;
            name: string;
        };
        CreateRosterGameDto: {
            /** @example League of Legends */
            name: string;
        };
        RosterEntry: {
            id: number;
            userId: number;
            gameId: number;
            handle: string;
            rank: string;
            role?: string;
            imageUrl?: string;
        };
        CreateRosterEntryDto: {
            /** @example John Doe */
            name: string;
            /** @example s123456 */
            sNumber: string;
            /** @example xXProGamerXx */
            handle: string;
            /** @example Diamond */
            rank: string;
            /** @example Support */
            role?: string | null;
            /** @example 1 */
            gameId: number;
        };
        /** @enum {string} */
        TimeTableType: "OPEN" | "CLOSED";
        TimeTableEntry: {
            id: number;
            dayOfWeek: number;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            label: string;
            type: components["schemas"]["TimeTableType"];
        };
        CreateTimeTableEntryDto: {
            /**
             * @description Day of week (1=Monday, 7=Sunday)
             * @example 1
             */
            dayOfWeek: number;
            /** @example 09:00 */
            startTime: string;
            /** @example 18:00 */
            endTime: string;
            /** @example Open Access */
            label: string;
            /** @enum {string} */
            type: "OPEN" | "CLOSED";
        };
        UpdateTimeTableEntryDto: {
            /** @example 09:00 */
            startTime: string;
            /** @example 18:00 */
            endTime: string;
            /** @example Open Access */
            label: string;
            /** @enum {string} */
            type: "OPEN" | "CLOSED";
        };
        Setting: {
            id: number;
            key: string;
            value: string;
        };
        UpdateFormDto: {
            title?: string;
            url?: string;
        };
        UpdateSettingDto: {
            /** @example googleFormUrl */
            key: string;
            /** @example https://forms.google.com/... */
            value: string;
        };
        AdminUser: {
            id: number;
            userId: number;
        };
        CreateAdminDto: {
            /**
             * @description Student email address (used as the User account email)
             * @example admin@student.ap.be
             */
            email: string;
            /**
             * @description Student number
             * @example s123456
             */
            sNumber: string;
            /**
             * @description Gmail address used for Google SSO login
             * @example admin@gmail.com
             */
            gmailEmail: string;
        };
        CreateEventDto: {
            /** @example League of Legends Tournament */
            title: string;
            /** @example 2026-03-15T18:00:00.000Z */
            startTime: string;
            /** @example 2026-03-15T22:00:00.000Z */
            endTime: string;
            /** @example Tournament */
            type: string;
        };
        UpdateEventDto: {
            /** @example Updated Tournament */
            title?: string;
            /** @example 2026-03-16T18:00:00.000Z */
            startTime?: string;
            /** @example 2026-03-16T22:00:00.000Z */
            endTime?: string;
            /** @example Casual */
            type?: string;
        };
        UserListItemDto: {
            id: number;
            name: string | null;
            email: string;
            sNumber: string;
            isAdmin: boolean;
            googleLinked: boolean;
            microsoftLinked: boolean;
            reservationCount: number;
            noShowCount: number;
        };
        WhitelistEntryDto: {
            email: string;
            userId: number;
            userEmail: string | null;
        };
        CreateWhitelistDto: {
            /**
             * @description External SSO email to pre-authorize
             * @example someone@gmail.com
             */
            email: string;
            /**
             * @description Target user id this email should link to once they sign in
             * @example 1
             */
            userId: number;
        };
        UserSsoLinkDto: {
            id: number;
            ssoId: string;
        };
        UserRecentReservationDto: {
            id: number;
            cuid: string;
            inventory: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            status: string;
        };
        UserDetailDto: {
            id: number;
            name: string | null;
            email: string;
            sNumber: string;
            isAdmin: boolean;
            googleLinks: components["schemas"]["UserSsoLinkDto"][];
            microsoftLinks: components["schemas"]["UserSsoLinkDto"][];
            reservationCount: number;
            noShowCount: number;
            recentReservations: components["schemas"]["UserRecentReservationDto"][];
        };
        UpdateUserDto: {
            name?: string;
            sNumber?: string;
            email?: string;
        };
        GoogleSSOUser: {
            id: number;
            ssoId: string;
            userId: number;
        };
        MicrosoftSSOUser: {
            id: number;
            ssoId: string;
            userId: number;
        };
        UserRelations: {
            reservations: components["schemas"]["Reservation"][];
            adminUsers: components["schemas"]["AdminUser"][];
            googleSSOUsers: components["schemas"]["GoogleSSOUser"][];
            microsoftSSOUsers: components["schemas"]["MicrosoftSSOUser"][];
            rosterEntries: components["schemas"]["RosterEntry"][];
        };
        User: {
            id: number;
            name?: string;
            email: string;
            sNumber: string;
        };
        AdminUserRelations: {
            user: components["schemas"]["User"];
        };
        GoogleSSOUserRelations: {
            user: components["schemas"]["User"];
        };
        MicrosoftSSOUserRelations: {
            user: components["schemas"]["User"];
        };
        SettingRelations: Record<string, never>;
        FormRelations: Record<string, never>;
        RosterGameRelations: {
            rosterEntries: components["schemas"]["RosterEntry"][];
        };
        RosterEntryRelations: {
            user: components["schemas"]["User"];
            game: components["schemas"]["RosterGame"];
        };
        ReservationRelations: {
            user: components["schemas"]["User"];
        };
        TimeTableEntryRelations: Record<string, never>;
        EventRelations: Record<string, never>;
        Form: {
            id: number;
            title: string;
            url: string;
        };
        Event: {
            id: number;
            title: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            type: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_googleAuthUrl: {
        parameters: {
            query?: {
                /** @description Frontend return URL path to preserve after login */
                returnUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthUrlResponseDto"];
                };
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query: {
                /** @description OAuth authorization code returned by Google */
                code: string;
                /** @description Optional state value sent during login request */
                state?: string;
                /** @description Issuer URL from Google */
                iss?: string;
                /** @description OAuth scopes granted */
                scope?: string;
                /** @description Authenticated user index */
                authuser?: string;
                /** @description Prompt type used */
                prompt?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_microsoftAuthUrl: {
        parameters: {
            query?: {
                /** @description Frontend return URL path to preserve after login */
                returnUrl?: string;
                /** @description If true, treat callback as a link-account flow for the currently authenticated user */
                linkMode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MicrosoftAuthUrlResponseDto"];
                };
            };
        };
    };
    AuthController_microsoftLogin: {
        parameters: {
            query?: {
                /** @description Frontend return URL path to preserve after login */
                returnUrl?: string;
                /** @description If true, treat callback as a link-account flow for the currently authenticated user */
                linkMode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_microsoftCallback: {
        parameters: {
            query: {
                /** @description OAuth authorization code returned by Microsoft */
                code: string;
                /** @description Opaque state value sent during login request (base64 JSON: { returnUrl, linkMode }) */
                state?: string;
                /** @description Session state from Microsoft */
                session_state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_listLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedProvidersResponseDto"];
                };
            };
        };
    };
    AuthController_unlinkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedProvidersResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    AuthController_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProfileResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReservationsController_findAll: {
        parameters: {
            query?: {
                date?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    ReservationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            /** @description Validation or business rule violation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
        };
    };
    ReservationsController_cancelByCuid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            /** @description Reservation is already cancelled or has already started */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
        };
    };
    ReservationsController_getSlots: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationSlotDto"][];
                };
            };
        };
    };
    ReservationsController_verifyByCuid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationVerificationDto"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
        };
    };
    ReservationsController_adminCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateReservationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            /** @description Time slot is already reserved */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
        };
    };
    ReservationsController_getNoShows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    ReservationsController_unBlockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            /** @description No no-shows found for this user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
        };
    };
    ReservationsController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReservationStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
        };
    };
    ReservationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReservationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReservationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpExceptionDto"];
                };
            };
        };
    };
    RosterController_findAllGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterGame"][];
                };
            };
        };
    };
    RosterController_createGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRosterGameDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterGame"];
                };
            };
        };
    };
    RosterController_deleteGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RosterController_findAllEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"][];
                };
            };
        };
    };
    RosterController_createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateRosterEntryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"];
                };
            };
        };
    };
    RosterController_deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimetableController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeTableEntry"][];
                };
            };
        };
    };
    TimetableController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimeTableEntryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeTableEntry"];
                };
            };
        };
    };
    TimetableController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimetableController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTimeTableEntryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeTableEntry"];
                };
            };
        };
    };
    SettingsController_getPublicSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"][];
                };
            };
        };
    };
    SettingsController_getInventorySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"][];
                };
            };
        };
    };
    SettingsController_getForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_updateForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFormDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_getAllSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"][];
                };
            };
        };
    };
    SettingsController_updateSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"];
                };
            };
        };
    };
    SettingsController_getAllAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
        };
    };
    SettingsController_createAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    SettingsController_removeAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_findUpcoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEventDto"][];
                };
            };
        };
    };
    EventsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEventDto"];
                };
            };
        };
    };
    EventsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEventDto"][];
                };
            };
        };
    };
    EventsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEventDto"];
                };
            };
        };
    };
    UsersController_list: {
        parameters: {
            query?: {
                /** @description Search by name, email or sNumber */
                search?: string;
                /** @description Only return admin users when "true" */
                adminOnly?: string;
                /** @description Only return users with active no-shows when "true" */
                noShowsOnly?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItemDto"][];
                };
            };
        };
    };
    UsersController_listWhitelist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitelistEntryDto"][];
                };
            };
        };
    };
    UsersController_createWhitelist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWhitelistDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deleteWhitelist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailDto"];
                };
            };
        };
    };
    UsersController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_promote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_demote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_unlinkSso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
