/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Google login URL */
        get: operations["AuthController_googleAuthUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to Google login page */
        get: operations["AuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback and session creation */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear auth cookie and logout */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile of authenticated user */
        get: operations["AuthController_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all reservations (Admin only) */
        get: operations["ReservationsController_findAll"];
        put?: never;
        /** Create a new reservation */
        post: operations["ReservationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/no-shows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all no-shows (Admin only) */
        get: operations["ReservationsController_getNoShows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update reservation status (Admin only) */
        patch: operations["ReservationsController_updateStatus"];
        trace?: never;
    };
    "/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a reservation (Admin only) */
        delete: operations["ReservationsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all roster games with entries */
        get: operations["RosterController_findAllGames"];
        put?: never;
        /** Create a new roster game (Admin only) */
        post: operations["RosterController_createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a roster game (Admin only) */
        delete: operations["RosterController_deleteGame"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all roster entries */
        get: operations["RosterController_findAllEntries"];
        put?: never;
        /** Add a roster entry (Admin only) */
        post: operations["RosterController_createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a roster entry (Admin only) */
        delete: operations["RosterController_deleteEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get upcoming events */
        get: operations["RosterController_findAllEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all timetable entries */
        get: operations["TimetableController_findAll"];
        put?: never;
        /** Create a timetable entry (Admin only) */
        post: operations["TimetableController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timetable/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a timetable entry (Admin only) */
        delete: operations["TimetableController_remove"];
        options?: never;
        head?: never;
        /** Update a timetable entry (Admin only) */
        patch: operations["TimetableController_update"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all settings (Admin only) */
        get: operations["SettingsController_getAllSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a setting (Admin only) */
        patch: operations["SettingsController_updateSetting"];
        trace?: never;
    };
    "/settings/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all admin users (Admin only) */
        get: operations["SettingsController_getAllAdmins"];
        put?: never;
        /** Add a new admin (Admin only) */
        post: operations["SettingsController_createAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/admins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an admin (Admin only) */
        delete: operations["SettingsController_removeAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GoogleAuthUrlResponseDto: {
            /**
             * @description Google OAuth login URL
             * @example https://accounts.google.com/o/oauth2/v2/auth?...
             */
            url: string;
        };
        LogoutResponseDto: {
            /** @example true */
            success: boolean;
        };
        AuthProfileResponseDto: {
            id: number;
            name: string | null;
            email: string;
            sNumber: string;
            /** @description Whether the authenticated user is an admin user */
            isAdmin: boolean;
        };
        CreateReservationDto: {
            /** @example s123456 */
            sNumber: string;
            /** @example student@student.ap.be */
            email: string;
            /**
             * @example pc
             * @enum {string}
             */
            inventory: "pc" | "ps5" | "switch";
            /** @example 2 */
            controllers: number;
            /** @example 2026-02-28T10:00:00.000Z */
            startTime: string;
            /** @example 2026-02-28T12:00:00.000Z */
            endTime: string;
        };
        /** @enum {string} */
        ReservationStatus: "RESERVED" | "CANCELLED" | "PRESENT" | "NO_SHOW";
        Reservation: {
            id: number;
            userId: number;
            controllers: number;
            email: string;
            inventory: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            status: components["schemas"]["ReservationStatus"];
        };
        UpdateReservationStatusDto: {
            /** @enum {string} */
            status: "RESERVED" | "CANCELLED" | "PRESENT" | "NO_SHOW";
        };
        RosterGame: {
            id: number;
            name: string;
        };
        CreateRosterGameDto: {
            /** @example League of Legends */
            name: string;
        };
        RosterEntry: {
            id: number;
            userId: number;
            gameId: number;
            handle: string;
            rank: string;
            role: string;
        };
        CreateRosterEntryDto: {
            /** @example John Doe */
            name: string;
            /** @example s123456 */
            sNumber: string;
            /** @example xXProGamerXx */
            handle: string;
            /** @example Diamond */
            rank: string;
            /** @example Support */
            role: string;
            /** @example 1 */
            gameId: number;
        };
        /** @enum {string} */
        TimeTableType: "OPEN" | "CLOSED";
        TimeTableEntry: {
            id: number;
            dayOfWeek: number;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            label: string;
            type: components["schemas"]["TimeTableType"];
        };
        CreateTimeTableEntryDto: {
            /**
             * @description Day of week (1=Monday, 7=Sunday)
             * @example 1
             */
            dayOfWeek: number;
            /** @example 09:00 */
            startTime: string;
            /** @example 18:00 */
            endTime: string;
            /** @example Open Access */
            label: string;
            /** @enum {string} */
            type: "OPEN" | "CLOSED";
        };
        UpdateTimeTableEntryDto: {
            /** @example 09:00 */
            startTime: string;
            /** @example 18:00 */
            endTime: string;
            /** @example Open Access */
            label: string;
            /** @enum {string} */
            type: "OPEN" | "CLOSED";
        };
        Setting: {
            id: number;
            key: string;
            value: string;
        };
        UpdateSettingDto: {
            /** @example googleFormUrl */
            key: string;
            /** @example https://forms.google.com/... */
            value: string;
        };
        AdminUser: {
            id: number;
            userId: number;
        };
        CreateAdminDto: {
            /** @example admin@student.ap.be */
            email: string;
        };
        GoogleSSOUser: {
            id: number;
            ssoId: string;
            userId: number;
        };
        UserRelations: {
            reservations: components["schemas"]["Reservation"][];
            adminUsers: components["schemas"]["AdminUser"][];
            googleSSOUsers: components["schemas"]["GoogleSSOUser"][];
            rosterEntries: components["schemas"]["RosterEntry"][];
        };
        User: {
            id: number;
            name?: string;
            email: string;
            sNumber: string;
        };
        AdminUserRelations: {
            user: components["schemas"]["User"];
        };
        GoogleSSOUserRelations: {
            user: components["schemas"]["User"];
        };
        SettingRelations: Record<string, never>;
        RosterGameRelations: {
            rosterEntries: components["schemas"]["RosterEntry"][];
        };
        RosterEntryRelations: {
            user: components["schemas"]["User"];
            game: components["schemas"]["RosterGame"];
        };
        ReservationRelations: {
            user: components["schemas"]["User"];
        };
        TimeTableEntryRelations: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_googleAuthUrl: {
        parameters: {
            query?: {
                /** @description Frontend return URL path to preserve after login */
                returnUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthUrlResponseDto"];
                };
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: {
                /** @description Frontend return URL path to preserve after login */
                returnUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query: {
                /** @description OAuth authorization code returned by Google */
                code: string;
                /** @description Optional state value sent during login request */
                state?: string;
                /** @description Issuer URL from Google */
                iss?: string;
                /** @description OAuth scopes granted */
                scope?: string;
                /** @description Authenticated user index */
                authuser?: string;
                /** @description Prompt type used */
                prompt?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    AuthController_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProfileResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReservationsController_findAll: {
        parameters: {
            query?: {
                date?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    ReservationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    ReservationsController_getNoShows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    ReservationsController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReservationStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    ReservationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RosterController_findAllGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterGame"][];
                };
            };
        };
    };
    RosterController_createGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRosterGameDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterGame"];
                };
            };
        };
    };
    RosterController_deleteGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RosterController_findAllEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"][];
                };
            };
        };
    };
    RosterController_createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRosterEntryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"];
                };
            };
        };
    };
    RosterController_deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RosterController_findAllEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    TimetableController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeTableEntry"][];
                };
            };
        };
    };
    TimetableController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimeTableEntryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeTableEntry"];
                };
            };
        };
    };
    TimetableController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimetableController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTimeTableEntryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeTableEntry"];
                };
            };
        };
    };
    SettingsController_getAllSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"][];
                };
            };
        };
    };
    SettingsController_updateSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"];
                };
            };
        };
    };
    SettingsController_getAllAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
        };
    };
    SettingsController_createAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    SettingsController_removeAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
